FROM node:16-alpine
WORKDIR /app
RUN apk --no-cache add --virtual builds-deps build-base python3
COPY package*.json ./
RUN npm install --location=global typescript
RUN npm ci
COPY . .
EXPOSE 5001
CMD ["npm", "run", "start:prod"]