FROM node:16-alpine
WORKDIR /app
RUN apk --no-cache add --virtual builds-deps build-base python3
COPY package*.json ./
RUN npm ci --only=production
RUN npm run build
COPY . .
EXPOSE 5000
CMD ["npm", "run", "start:prod"]